name: Generate ASCII Artwork
on:
  push:
jobs:
  ascii_artwork-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5.0.0

      - name: ASCII Artwork Shell Script
        run: |
          chmod +x ascii-artwork.sh
          ./ascii-artwork.sh

      # - name: Install Cowsay
      #   run: sudo apt-get update && sudo apt-get install cowsay -y

      # - name: Execute Cowsay
      #   run: cowsay -f dragon "Run for cover, I am a DRAGON" >> dragon.txt

      # - name: Verify Output
      #   run: grep -i "dragon" dragon.txt

      # - name: Display Artwork
      #   run: cat dragon.txt

      # - name: List Repository Files
      #   run: ls -ltra
