name: ASCII Artwork
on: push
jobs:
  ascii-artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0
      - name: Install Cowsay
        run: |
          echo "Hello World!"
          echo "Welcome to GitHub Actions"
          cat README.md