name: My First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello world!"
      - name: Welcome Message
        run: echo "Welcome to GitHub Actions"
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0
      - name: Display README
        run: cat README.md